### ISSUE TITLE
Communicate Page

### ISSUE THREAD

**Issue by chukon** [rvcapps/niurvc#18]
- Get icons
- Create Needed Pages
- Get Data

**Comment by MrxHouse** [comment]
I'm a little confused, do you want me to mark up a web page in HTML and CSS and embed a youtube video? For now, I had thought I was editing a page previously used. I apologize for the major confusion.

**Comment by MrxHouse** [comment]
If so, then I am currently working on a web page as we speak.

**Comment by chukon** [comment]
This is my issue. Your issue is only the media page where you are using the Google page to add videos and images. See https://github.com/rvcapps/niurvc/issues/9
