### ISSUE TITLE
Media page updated 

### ISSUE THREAD

**Issue by chukon** [rvcapps/niurvc#31]
Test that you can access photo and video page.

**Comment by MrxHouse** [comment]
I did yesterday, I cannot.

**Comment by chukon** [comment]
Go to Media tab and tap on Photos Or Videos. Others have tested this and commented that it does work.

**Comment by MrxHouse** [comment]
I can only access the photo gallery. There was an issue where the page stalls and redirects to photos when choosing the video tab. The photo tab works but it zooms in on a picture automatically, you have to exit off the photo after opening it.
