### ISSUE TITLE
Connections Page

### ISSUE THREAD

**Issue by chukon** [rvcapps/niurvc#8]
- Add icons to "Connections" page (see below)
- Create new viewcontroller for each icon (see below)
- Push dummy content on their for now. (see below)

See [link](http://www.rvchourofcode.com/niurvc.html)

![connections](https://user-images.githubusercontent.com/3256516/29379274-8e510b90-8287-11e7-865e-aebab9521eb6.png)
![happenings](https://user-images.githubusercontent.com/3256516/29379412-01fa4e94-8288-11e7-8c89-0cabe1b9ae8d.png)
![importantlinks](https://user-images.githubusercontent.com/3256516/29379411-01f9327a-8288-11e7-9b5f-6875f53a3945.png)
![jobsinternships](https://user-images.githubusercontent.com/3256516/29379408-01f1da7a-8288-11e7-9ad9-541849eb0b95.png)
![partners](https://user-images.githubusercontent.com/3256516/29379410-01f5fc04-8288-11e7-85dd-7a6bb3d9c783.png)
![scholarships](https://user-images.githubusercontent.com/3256516/29379407-01f1032a-8288-11e7-84a0-4893e74c3950.png)
![socialmedia](https://user-images.githubusercontent.com/3256516/29379409-01f6a988-8288-11e7-9c16-3dabbb810aae.png)

**Comment by chukon** [comment]
Jesus - all the icons need to be the RVC Blue color.

See [marketing colors](http://www.rockvalleycollege.edu/About/Marketing/index.cfm)

**Comment by chukon** [comment]
I won't be on campus for today. If you need help make a comment in issue on Github.

As soon as I get access common spot I will let you know.

**Comment by chukon** [comment]
Jesus, I would like to have the connection pages done by Sept 9th. Ok? I will do a pull request at that time.

**Comment by jequeza** [comment]
Sorry for the late reply, work has been little busy. 

I have all of the connections view controllers laid out and about 80% completed on the content that they will be having. I will be shooting you some emails this coming days with some issues I encountered along the way. Most of it is due to the fact that I don't have much experience and the content is new to me. But I think I'll be completed by the deadline. 

Have a wonderful day.

**Comment by chukon** [comment]
Here is example you requested for sub tab pages for connections. See https://github.com/ioscourse/TabExample

**Comment by chukon** [comment]
Jesus, you need to remove one of the tab pages (Apple only allows 5 tabs now).

See https://github.com/ioscourse/TabExample

**Comment by chukon** [comment]
Jesus, I need you to update the below repo with your changes in order to do a pull request. It looks like you created a separate repo.

https://github.com/jequeza/niurvc 

Let me know when this is completed.
